// <auto-generated />
using System;
using Amrit.Tulya.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amrit.Tulya.Migrations
{
    [DbContext(typeof(TeaShopContext))]
    [Migration("20200713173642_Amrit.Tulya.DB")]
    partial class AmritTulyaDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Amrit.Tulya.Models.TeaInventory", b =>
                {
                    b.Property<int>("TeaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Tea_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Created_Date")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TeaDescription")
                        .HasColumnName("Tea_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeaImagePath")
                        .HasColumnName("Tea_Image_Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeaName")
                        .IsRequired()
                        .HasColumnName("Tea_Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("TeaPrice")
                        .HasColumnName("Tea_Price")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("TeaId")
                        .HasName("PK__Tea_Inve__16876EE263C641E4");

                    b.ToTable("Tea_Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
